"""
Make database models importable

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/database/models/__init__.py.j2 instead.
"""

# isort: skip_file

from platformics.database.models.base import Base, meta  # noqa: F401
