repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: "v0.6.0"
  hooks:
  - id: ruff-format
  - id: ruff
    args:
    - --fix
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v1.10.0"
  hooks:
  - id: mypy
    args:
      - --namespace-packages
      - --explicit-package-bases
    exclude: "platformics/thirdparty|platformics/graphql_api/relay"
    additional_dependencies: ["types-PyYAML", "types-dateparser", "types-requests"]
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0
  hooks:
  - id: check-toml
  - id: check-yaml
  - id: check-json
    exclude: "launch.json"
  - id: check-merge-conflict
  - id: end-of-file-fixer
  - id: trailing-whitespace
