FROM python:3.11-slim-bookworm AS build
RUN apt-get update && \
    apt-get install -y vim wget nginx nginx-extras procps ripgrep make gcc && \
    apt-get clean

ENV POETRY_VERSION=1.7
# Some base python dependencies to kickstart our container build.
RUN python3 -m pip install --no-cache-dir poetry==$POETRY_VERSION supervisor

RUN mkdir -p /app
WORKDIR /app

COPY pyproject.toml poetry.lock ./
RUN poetry config virtualenvs.create false
ENV PYTHONPATH=.
RUN mkdir -p platformics
RUN touch platformics/__init__.py
RUN touch README.md
RUN poetry install

# Ordering is important here. Entities first!
COPY test_app/ .
COPY platformics ./platformics

CMD ["/usr/local/bin/supervisord", "-c", "/app/etc/supervisord.conf"]
