id: https://czid.org/entities/schema/platformics
title: CZID Platformics Bio-Entities Schema
name: platformics

imports:
  - linkml:types
prefixes:
  linkml:
    prefix_prefix: linkml
    prefix_reference: https://w3id.org/linkml/

types:
  string:
    description: A character string
    base: string
    uri: xsd:string

  integer:
    base: integer
    uri: xsd:integer

  uuid:
    uri: xsd:string
    typeof: string
    base: string
    description: A UUID

enums:
  HomeworkScoreType:
    description: Types of homework scores
    permissible_values:
      Penmanship:
        description: A binary mask volume
      Composition:
        description: A series of coordinates and an orientation
      Content:
        description: A series of coordinates
  FileStatus:
    permissible_values:
      SUCCESS:
      FAILED:
      PENDING:
  FileAccessProtocol:
    permissible_values:
      s3:
        description: This file is accessible via the (AWS) S3 protocol
      https:
        description: This file is accessible via the HTTPS protocol
  NucleicAcid:
    permissible_values:
      RNA:
      DNA:
  SequencingProtocol:
    permissible_values:
      MNGS:
      TARGETED:
      MSSPE:
  SequencingTechnology:
    permissible_values:
      Illumina:
      Nanopore:

classes:
  Entity:
    attributes:
      id:
        identifier: true
        range: uuid
        readonly: true # The API handles generating the values for these fields
        required: true
        annotations:
          default_value_callable: uuid6.uuid7
      type:
        range: string
        designates_type: true
        annotations:
          hidden: true
      producing_run_id:
        range: uuid
        annotations:
          mutable: false # This field can't be modified by an `Update` mutation
          system_writable_only: True
      owner_user_id:
        range: integer
        minimum_value: 0
        required: true
        readonly: true
      collection_id:
        range: integer
        minimum_value: 0
        required: True
      created_at:
        range: date
        required: true
        readonly: true
        annotations:
          default_sa_function: now()
      updated_at:
        range: date
        readonly: true
        annotations:
          onupdate: datetime.datetime.now
      deleted_at:
        range: date
        annotations:
          mutable: true
          system_writable_only: True
    annotations:
      plural: Entities

  File:
    is_a: Entity
    mixins:
      - EntityMixin
    annotations:
      plural: Files
    attributes:
      status:
        range: FileStatus
        required: true
      protocol:
        range: FileAccessProtocol
        required: true
      # Bucket name
      namespace:
        range: string
        required: true
      # Prefix (does not start with /)
      path:
        range: string
        required: true
      file_format:
        range: string
        required: true
      compression_type:
        range: string
      size:
        range: integer
        minimum_value: 0
      # Information about file upload (optional)
      upload_client:
        range: string
      upload_error:
        range: string

  Sample:
    is_a: Entity
    mixins:
      - EntityMixin
    attributes:
      name:
        range: string
        required: true
        annotations:
          minimum_length: 4
          maximum_length: 128
      sample_type:
        range: string
        required: true
      water_control:
        range: boolean
        required: true
      collection_date:
        range: date
      collection_location:
        range: string
        required: true
      description:
        range: string
      sequencing_reads:
        range: SequencingRead
        multivalued: true
        inverse: SequencingRead.sample
        annotations:
          cascade_delete: true
      system_mutable_field:
        range: string
        annotations:
          system_writable_only: True
    annotations:
      plural: Samples

  SequencingRead:
    is_a: Entity
    mixins:
      - EntityMixin
    attributes:
      sample:
        range: Sample
        inverse: Sample.sequencing_reads
      protocol:
        range: SequencingProtocol
        required: true
      r1_file:
        range: File
        readonly: true
        annotations:
          cascade_delete: true
          single_parent: true
      r2_file:
        range: File
        readonly: true
        annotations:
          cascade_delete: true
          single_parent: true
      technology:
        range: SequencingTechnology
        required: true
      nucleic_acid:
        range: NucleicAcid
        required: true
      primer_file:
        range: GenomicRange
        inverse: GenomicRange.sequencing_reads
        # Only mutable by system user (needed for upload flow)
        annotations:
          mutable: true
          system_writable_only: True
      contig:
        range: Contig
        inverse: Contig.sequencing_reads
        annotations:
          mutable: false
    annotations:
      plural: SequencingReads

  GenomicRange:
    is_a: Entity
    mixins:
      - EntityMixin
    attributes:
      file:
        range: File
        readonly: true
        annotations:
          cascade_delete: true
          single_parent: true
      sequencing_reads:
        range: SequencingRead
        inverse: SequencingRead.primer_file
        multivalued: true
    annotations:
      plural: GenomicRanges

  Contig:
    is_a: Entity
    mixins:
      - EntityMixin
    attributes:
      sequencing_reads:
        range: SequencingRead
        inverse: SequencingRead.contig
        multivalued: true
      sequence:
        range: string
        required: true
      upstream_database:
        range: UpstreamDatabase
        inverse: UpstreamDatabase.contig
        required: true
        annotations:
          mutable: false
    annotations:
      plural: Contigs

  Student:
    mixins:
      - IntIDMixin
    attributes:
      name:
        range: string
        required: true
      grade:
        range: integer
      school:
        range: School
        inverse: School.students
      homework_assignments:
        range: HomeworkAssignment
        inverse: homework_assignments.student
        multivalued: true
    annotations:
      plural: Students

  Teacher:
    mixins:
      - IntIDMixin
    attributes:
      name:
        range: string
        required: true
      subject:
        range: string
      school:
        range: School
        inverse: School.teachers
    annotations:
      plural: Teachers

  School:
    mixins:
      - IntIDMixin
    attributes:
      name:
        range: string
        required: true
      min_grade:
        range: integer
      max_grade:
        range: integer
      students:
        description: Students who go to this school
        multivalued: true
        inverse: Student.school
        range: Student
      teachers:
        description: Teacher who teach at this school
        multivalued: true
        inverse: Teacher.school
        range: Teacher
      district:
        range: District
        inverse: District.schools
    annotations:
      plural: Schools

  HomeworkAssignment:
    mixins:
      - IntIDMixin
    attributes:
      student:
        range: Student
        inverse: Student.homework_assignments
      name:
        range: string
        required: true
      scores:
        range: HomeworkScore
        inverse: HomeworkScore.homework_assignment
        multivalued: true
    annotations:
      plural: HomeworkAssignments

  HomeworkScore:
    mixins:
      - IntIDMixin
    attributes:
      homework_assignment:
        range: HomeworkAssignment
        inverse: HomeworkAssignment.scores
      score_type:
        range: HomeworkScoreType
      score_value:
        range: integer
        required: true
    annotations:
      plural: HomeworkScores

  District:
    mixins:
      - IntIDMixin
    attributes:
      name:
        range: string
        required: true
      location:
        range: string
        required: true
      schools:
        description: Schools in the district
        multivalued: true
        inverse: Schoool.district
        range: School
    annotations:
      plural: Districts

  NotGenerated:
    mixins:
      - IntIDMixin
    attributes:
      name:
        range: string
        required: true
    annotations:
      plural: NotGenerateds
      skip_codegen: true

  IntIDMixin:
    mixin: true
    attributes:
      id:
        identifier: true
        description: Numeric identifier
        range: integer
        required: true
        annotations:
          auto_increment: true
      # Just included for auth reasons
      owner_user_id:
        range: integer
        minimum_value: 0
        required: true
      collection_id:
        range: integer
        minimum_value: 0
        required: True

  EntityMixin:
    mixin: true
    attributes:
      entity_id:
        required: true
        readonly: true
        range: uuid
        identifier: true
        inverse: entity.id
        annotations:
          hidden: true

  UpstreamDatabase:
    is_a: Entity
    mixins:
      - EntityMixin
    attributes:
      name:
        range: string
        required: true
        annotations:
          indexed: true
      contig:
        range: Contig
        inverse: Contig.upstream_database
        multivalued: true
      # This is where NCBI indexes would live
    annotations:
      plural: UpstreamDatabases

  ConstraintCheckedType:
    is_a: Entity
    mixins:
      - EntityMixin
    attributes:
      length_3_to_8:
        range: string
        annotations:
          minimum_length: 3
          maximum_length: 8
      field with spaces:
        range: string
      regex_format_check:
        range: string
        pattern: '\d{3}-\d{2}-\d{4}'
      min_value_0:
        range: integer
        minimum_value: 0
      enum_field:
        range: NucleicAcid
      bool_field:
        range: boolean
      max_value_9:
        range: integer
        maximum_value: 9
      min_value_0_max_value_9:
        range: integer
        minimum_value: 0
        maximum_value: 9
      float_1dot1_to_2dot2:
        range: float
        minimum_value: 1.1
        maximum_value: 2.2
      no_string_checks:
        range: string
      no_int_checks:
        range: integer
      no_float_checks:
        range: float
    annotations:
      plural: ConstraintCheckedTypes

  SystemWritableOnlyType:
    is_a: Entity
    mixins:
      - EntityMixin
    attributes:
      name:
        range: string
        required: true
    annotations:
      system_writable_only: true
      plural: SystemWritableOnlyTypes

  ImmutableType:
    is_a: Entity
    mixins:
      - EntityMixin
    attributes:
      name:
        range: string
        required: true
    annotations:
      mutable: false
      plural: ImmutableTypes

  UncaughtException:
    mixins:
      - IntIDMixin
    attributes:
      name:
        range: string
        required: true
    annotations:
      mutable: false
      plural: UncaughtExceptions
