id: https://czid.org/entities/schema/platformics
title: CZID Platformics Bio-Entities Schema
name: platformics
default_range: string

types:
  string:
    uri: xsd:string
    base: str
    description: A character string

  integer:
    uri: xsd:integer
    base: int
    description: An integer

  uuid:
    uri: xsd:string
    typeof: str
    base: str
    description: A UUID

enums:
  FileStatus:
    permissible_values:
      SUCCESS:
      FAILED:
      PENDING:
  FileAccessProtocol:
    permissible_values:
      s3:
        description: This file is accessible via the (AWS) S3 protocol
      https:
        description: This file is accessible via the HTTPS protocol
  NucleicAcid:
    permissible_values:
      RNA:
      DNA:
  SequencingProtocol:
    permissible_values:
      MNGS:
      TARGETED:
      MSSPE:
  SequencingTechnology:
    permissible_values:
      Illumina:
      Nanopore:

classes:
  Entity:
    attributes:
      id:
        identifier: true
        range: uuid
        readonly: true # The API handles generating the values for these fields
        required: true
      type:
        range: string
        designates_type: true
        annotations:
          hidden: true
      producing_run_id:
        range: uuid
        annotations:
          system_writable_only: True
      owner_user_id:
        range: integer
        minimum_value: 0
        required: true
        readonly: true
      collection_id:
        range: integer
        minimum_value: 0
        required: True
      created_at:
        range: date
        required: true
        readonly: true
      updated_at:
        range: date
        readonly: true
    annotations:
      plural: Entities
 
  File:
    attributes:
      id:
        identifier: true
        range: uuid
        required: true
      # This file's ID is stored in the entity column <entity_field_name>_id
      entity_field_name:
        range: string
        required: true
      # Which entity this file is connected to
      entity:
        range: Entity
        required: true
      status:
        range: FileStatus
        required: true
      protocol:
        range: FileAccessProtocol
        required: true
      # Bucket name
      namespace:
        range: string
        required: true
      # Prefix (does not start with /)
      path:
        range: string
        required: true
      file_format:
        range: string
        required: true
      compression_type:
        range: string
      size:
        range: integer
        minimum_value: 0
      # Information about file upload (optional)
      upload_client:
        range: FileUploadClient
      upload_error:
        range: string
      created_at:
        range: date
        required: true
        readonly: true
      updated_at:
        range: date
        readonly: true

  Sample:
    is_a: Entity
    mixins:
      - EntityMixin
    attributes:
      name:
        range: string
        required: true
        annotations:
          minimum_length: 4
          maximum_length: 128
      sample_type:
        range: string
        required: true
      water_control:
        range: boolean
        required: true
      collection_date:
        range: date
      collection_location:
        range: string
        required: true
      description:
        range: string
      sequencing_reads:
        range: SequencingRead
        multivalued: true
        inverse: SequencingRead.sample
    annotations:
      plural: Samples

  SequencingRead:
    is_a: Entity
    mixins:
      - EntityMixin
    attributes:
      sample:
        range: Sample
        inverse: Sample.sequencing_reads
      protocol:
        range: SequencingProtocol
        required: true
      r1_file:
        range: File
      r2_file:
        range: File
      technology:
        range: SequencingTechnology
        required: true
      nucleic_acid:
        range: NucleicAcid
        required: true
      has_ercc:
        range: boolean
        required: true
      primer_file:
        range: GenomicRange
        inverse: GenomicRange.sequencing_reads
      contigs:
        range: Contig
        inverse: Contig.sequencing_read
        multivalued: true
    annotations:
      plural: SequencingReads

  GenomicRange:
    is_a: Entity
    mixins:
      - EntityMixin
    attributes:
      file:
        range: File
      sequencing_reads:
        range: SequencingRead
        inverse: SequencingRead.primer_file
        multivalued: true
    annotations:
      plural: GenomicRanges

  Contig:
    is_a: Entity
    mixins:
      - EntityMixin
    attributes:
      sequencing_read:
        range: SequencingRead
        inverse: Sample.contigs
      sequence:
        required: true
    annotations:
      plural: Contigs

  EntityMixin:
    mixin: true
    attributes:
      entity_id:
        required: true
        readonly: true
        range: uuid
        identifier: true
        inverse: entity.id
        annotations:
          hidden: true
