"""
Supported GraphQL queries for files and entities

Auto-generated by running 'make codegen'. Do not edit.
Make changes to the template codegen/templates/api/queries.py.j2 instead.
"""

import strawberry
from strawberry import relay
from typing import Sequence, List
from api.files import File, resolve_files
from api.types.sample import Sample, resolve_samples, SampleAggregate, resolve_samples_aggregate
from api.types.sequencing_read import (
    SequencingRead,
    resolve_sequencing_reads,
    SequencingReadAggregate,
    resolve_sequencing_reads_aggregate,
)
from api.types.genomic_range import (
    GenomicRange,
    resolve_genomic_ranges,
    GenomicRangeAggregate,
    resolve_genomic_ranges_aggregate,
)
from api.types.contig import Contig, resolve_contigs, ContigAggregate, resolve_contigs_aggregate


@strawberry.type
class Query:
    # Allow relay-style queries by node ID
    node: relay.Node = relay.node()
    nodes: List[relay.Node] = relay.node()
    # Query files
    files: Sequence[File] = resolve_files

    # Query entities
    samples: Sequence[Sample] = resolve_samples
    sequencing_reads: Sequence[SequencingRead] = resolve_sequencing_reads
    genomic_ranges: Sequence[GenomicRange] = resolve_genomic_ranges
    contigs: Sequence[Contig] = resolve_contigs

    # Query entity aggregates
    samples_aggregate: SampleAggregate = resolve_samples_aggregate
    sequencing_reads_aggregate: SequencingReadAggregate = resolve_sequencing_reads_aggregate
    genomic_ranges_aggregate: GenomicRangeAggregate = resolve_genomic_ranges_aggregate
    contigs_aggregate: ContigAggregate = resolve_contigs_aggregate

    @strawberry.field
    def uncaught_exception(self) -> str:
        # Trigger an AttributeException
        return self.kaboom
