name: Test pushing docker repo

on: push
permissions:
  packages: write

jobs:
  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: install poetry
        run: |
          python -m pip install --no-cache-dir poetry==1.8 supervisor
          poetry self add "poetry-dynamic-versioning[plugin]"

      - name: Build with Poetry
        run: make build-wheel

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}-test:sometag
