name: Build and push docker image and package

on:
  release:
    types: 
      - published
  push:
    branches:
      - ninabernick/package
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/${{ github.repository }}
    permissions:
      id-token: write # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - name: checkout code
      uses: actions/checkout@v4
    - name: set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: install poetry
      run: |
        python -m pip install --no-cache-dir poetry==1.8 supervisor
        poetry self add "poetry-dynamic-versioning[plugin]"

    - name: set up docker
      run: |
        make gha-setup

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build with Poetry
      run: make build-wheel

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        # push: true #TODO add back
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.event.release.tag_name }}
          ghcr.io/${{ github.repository }}:latest

    - name: Publish package distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/ #TODO remove when ready to publish

