name: Release Please

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Run release-please
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Generate token
      id: generate_token
      uses: chanzuckerberg/github-app-token@v1.1.4
      with:
        app_id: ${{ secrets.CZI_RELEASE_PLEASE_APP_ID }}
        private_key: ${{ secrets.CZI_RELEASE_PLEASE_PK }}

    - name: Run release-please
      uses: google-github-actions/release-please-action@v3
      with:
        release-type: python
        token: ${{ steps.generate_token.outputs.token }}
        bump-minor-pre-major: true