name: "Run tests on push"

on:
  push:
    branches:
      - '**'

jobs:
  pytest:
    name: "Pytest"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
    - name: "Set up Python"
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    
    - name: "Install dependencies"
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: "Run tests"
      run: |
        make test
