name: "Run tests on push"

on:
  push:
    branches:
      - '**'

jobs:
  pytest:
    name: "Pytest"
    runs-on: ubuntu-latest

    steps:
    - name: "Checkout code"
      uses: actions/checkout@v4
    - name: "Set up Python"
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: "Install poetry"
      run: |
        python -m pip install --no-cache-dir poetry==1.8 supervisor
    
    - name: "Set up docker"
      run: |
        make gha-setup

    - name: "Build docker image"
      run: |
        make build

    
    - name: "Run tests"
      run: |
        make test
